version: '3.7'

networks:
  default:
    external:
      name: sagemaker-local

services:
  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
    container_name: minio
    command: server /data
    volumes:
      - ./data/minio:/data
    restart: unless-stopped
    env_file: config.env
  rl_coach:
    image: mattcamp/dr-coach:latest
    env_file: config.env
    container_name: coach
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './src/rl_coach_2020_v2:/deepracer/rl_coach'
    - '/robo/container:/robo/container'
    depends_on:
    - minio
  robomaker:
    image: awsdeepracercommunity/deepracer-robomaker:cpu-avx2
    command: ["${ROBOMAKER_COMMAND}"]
    volumes:
      - ./data/robomaker:/root/.ros/
    ports:
      - "127.0.0.1:8080:5900"
      - "127.0.0.1:8888:8080"
    container_name: robomaker
    restart: unless-stopped
    env_file: config.env
    depends_on:
    - rl_coach
