"""empty message

Revision ID: 79e6dc281387
Revises: 
Create Date: 2020-04-27 11:36:20.080369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e6dc281387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('track', sa.String(length=120), nullable=True),
    sa.Column('reward_function_filename', sa.String(length=120), nullable=True),
    sa.Column('model_metadata_filename', sa.String(length=128), nullable=True),
    sa.Column('race_type', sa.String(length=32), nullable=True),
    sa.Column('number_of_obstacles', sa.Integer(), nullable=True),
    sa.Column('obstacle_type', sa.String(length=16), nullable=True),
    sa.Column('randomize_obstacle_locations', sa.Boolean(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('episodes_between_training', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('discount_factor', sa.Float(), nullable=True),
    sa.Column('loss_type', sa.String(length=64), nullable=True),
    sa.Column('change_start_position', sa.Boolean(), nullable=True),
    sa.Column('alternate_direction', sa.Boolean(), nullable=True),
    sa.Column('pretrained_model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('episodes_trained', sa.Integer(), nullable=True),
    sa.Column('laps_complete', sa.Integer(), nullable=True),
    sa.Column('average_pct_complete', sa.Float(), nullable=True),
    sa.Column('best_lap_time', sa.Float(), nullable=True),
    sa.Column('minutes_target', sa.Integer(), nullable=True),
    sa.Column('minutes_trained', sa.Integer(), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_job_name'), 'training_job', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_job_name'), table_name='training_job')
    op.drop_table('training_job')
    # ### end Alembic commands ###
