"""empty message

Revision ID: 7a6f073df1c0
Revises: 2cd1647ab9be
Create Date: 2020-04-24 13:35:53.504266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6f073df1c0'
down_revision = '2cd1647ab9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_job', sa.Column('minutes_target', sa.Integer(), nullable=True))
    op.add_column('training_job', sa.Column('start_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_job', 'start_timestamp')
    op.drop_column('training_job', 'minutes_target')
    # ### end Alembic commands ###
