"""empty message

Revision ID: 9aea328730f0
Revises: 
Create Date: 2020-05-01 13:03:30.233000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aea328730f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('track', sa.String(length=120), nullable=True),
    sa.Column('reward_function_filename', sa.String(length=120), nullable=True),
    sa.Column('model_metadata_filename', sa.String(length=128), nullable=True),
    sa.Column('episodes_between_training', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('discount_factor', sa.Float(), nullable=True),
    sa.Column('loss_type', sa.String(length=64), nullable=True),
    sa.Column('change_start_position', sa.Boolean(), nullable=True),
    sa.Column('alternate_direction', sa.Boolean(), nullable=True),
    sa.Column('pretrained_model', sa.String(length=128), nullable=True),
    sa.Column('nn_layers', sa.Integer(), nullable=True),
    sa.Column('sensor_stereo_cameras', sa.Boolean(), nullable=True),
    sa.Column('sensor_lidar', sa.Boolean(), nullable=True),
    sa.Column('race_type', sa.String(length=32), nullable=True),
    sa.Column('number_of_obstacles', sa.Integer(), nullable=True),
    sa.Column('obstacle_type', sa.String(length=16), nullable=True),
    sa.Column('randomize_obstacle_locations', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('episodes_target', sa.Integer(), nullable=True),
    sa.Column('episodes_trained', sa.Integer(), nullable=True),
    sa.Column('laps_complete', sa.Integer(), nullable=True),
    sa.Column('average_pct_complete', sa.Float(), nullable=True),
    sa.Column('best_lap_time', sa.Float(), nullable=True),
    sa.Column('best_lap_episode', sa.Integer(), nullable=True),
    sa.Column('minutes_target', sa.Integer(), nullable=True),
    sa.Column('minutes_trained', sa.Integer(), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_model_name'), 'local_model', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_local_model_name'), table_name='local_model')
    op.drop_table('local_model')
    # ### end Alembic commands ###
