"""empty message

Revision ID: ab23e8674b4a
Revises: 79e6dc281387
Create Date: 2020-04-27 12:10:07.152021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab23e8674b4a'
down_revision = '79e6dc281387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_job_name', table_name='training_job')
    op.drop_table('training_job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('track', sa.VARCHAR(length=120), nullable=True),
    sa.Column('reward_function_filename', sa.VARCHAR(length=120), nullable=True),
    sa.Column('model_metadata_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('race_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('number_of_obstacles', sa.INTEGER(), nullable=True),
    sa.Column('obstacle_type', sa.VARCHAR(length=16), nullable=True),
    sa.Column('randomize_obstacle_locations', sa.BOOLEAN(), nullable=True),
    sa.Column('episodes', sa.INTEGER(), nullable=True),
    sa.Column('episodes_between_training', sa.INTEGER(), nullable=True),
    sa.Column('batch_size', sa.INTEGER(), nullable=True),
    sa.Column('epochs', sa.INTEGER(), nullable=True),
    sa.Column('learning_rate', sa.FLOAT(), nullable=True),
    sa.Column('entropy', sa.FLOAT(), nullable=True),
    sa.Column('discount_factor', sa.FLOAT(), nullable=True),
    sa.Column('loss_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('change_start_position', sa.BOOLEAN(), nullable=True),
    sa.Column('alternate_direction', sa.BOOLEAN(), nullable=True),
    sa.Column('pretrained_model', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.Column('episodes_trained', sa.INTEGER(), nullable=True),
    sa.Column('laps_complete', sa.INTEGER(), nullable=True),
    sa.Column('average_pct_complete', sa.FLOAT(), nullable=True),
    sa.Column('best_lap_time', sa.FLOAT(), nullable=True),
    sa.Column('minutes_target', sa.INTEGER(), nullable=True),
    sa.Column('minutes_trained', sa.INTEGER(), nullable=True),
    sa.Column('start_timestamp', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('alternate_direction IN (0, 1)'),
    sa.CheckConstraint('change_start_position IN (0, 1)'),
    sa.CheckConstraint('randomize_obstacle_locations IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_job_name', 'training_job', ['name'], unique=1)
    # ### end Alembic commands ###
