"""empty message

Revision ID: b08dad89cc15
Revises: 9aea328730f0
Create Date: 2020-05-05 20:52:41.805394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08dad89cc15'
down_revision = '9aea328730f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_model', sa.Column('bot_car_speed', sa.Float(), nullable=True))
    op.add_column('local_model', sa.Column('crashes', sa.Integer(), nullable=True))
    op.add_column('local_model', sa.Column('is_lane_change', sa.Boolean(), nullable=True))
    op.add_column('local_model', sa.Column('lower_lane_change_time', sa.Integer(), nullable=True))
    op.add_column('local_model', sa.Column('number_of_bot_cars', sa.Integer(), nullable=True))
    op.add_column('local_model', sa.Column('off_tracks', sa.Integer(), nullable=True))
    op.add_column('local_model', sa.Column('upper_lane_change_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_model', 'upper_lane_change_time')
    op.drop_column('local_model', 'off_tracks')
    op.drop_column('local_model', 'number_of_bot_cars')
    op.drop_column('local_model', 'lower_lane_change_time')
    op.drop_column('local_model', 'is_lane_change')
    op.drop_column('local_model', 'crashes')
    op.drop_column('local_model', 'bot_car_speed')
    # ### end Alembic commands ###
